### ISSUE TITLE
[Feature Request] Generate placeholders for previously uploaded images

### ISSUE THREAD

**Issue by EGGamer** [WalkingPizza/strapi-plugin-placeholder#1]
It would be nice if the plugin had a button to generate placeholders for already uploaded images before the plugin was installed (or if it did it automatically). Otherwise, we need to re-upload them and in large-scale projects it might not be easy

**Comment by WalkingPizza** [comment]
Hey @EGGamer!
It's a very nice idea, so it'll be there eventually, I just have to figure out the most performant way of doing it!

**Comment by niklasfjeldberg** [comment]
@WalkingPizza any update on this?

**Comment by WalkingPizza** [comment]
Apologies for the delay.

You can now do this by copying [this gist](https://gist.github.com/WalkingPizza/72dc3d96ddeb9de00f981e0ec14c7938) into your `./database/migrations` folder and starting your Strapi instance!

It basically retrieves `BATCH_SIZE` files at a time, making sure to only retrieve those that have a mime type starting with `image/`, a URL and no placeholder value, and then tries to generate and update the placeholder.

Let me know if it works!

**Comment by RilDev** [comment]
It worked for me, thanks!

**Comment by eso519** [comment]
> Apologies for the delay.
> 
> You can now do this by copying [this gist](https://gist.github.com/WalkingPizza/72dc3d96ddeb9de00f981e0ec14c7938) into your `./database/migrations` folder and starting your Strapi instance!
> 
> It basically retrieves `BATCH_SIZE` files at a time, making sure to only retrieve those that have a mime type starting with `image/`, a URL and no placeholder value, and then tries to generate and update the placeholder.
> 
> Let me know if it works!

Works nicely. Thank you!

**Comment by ghost** [comment]
A couple of important details:

- You need to run strapi once with the placeholder plugin installed before trying to use this migration script (otherwise, the placeholder column won't exist and it will fail)
- If your database is mysql and you character encoding is utf8mb4, replace .andWhereLike with .andWhereILike on line 14. This is due to a bug in knex's implementation of whereLike that forces the collation to utf8_bin which is not compatible with utf8mb4 https://github.com/knex/knex/issues/5143

Hope this helps someone!

**Comment by yasssuz** [comment]
Closing issue as feature was implemented and README was updated https://github.com/WalkingPizza/strapi-plugin-placeholder/pull/5
